service: dtp-fullstack-api

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules:
      forceExclude:
        - aws-sdk
    packager: 'yarn'
    excludeFiles: src/**/*.test.[t|j]s

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  stage: ${opt:stage, "local"}
  region: eu-west-1
  environment:
    STAGE: ${self:provider.stage}

functions:
  movieSearch:
    handler: src/index.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
